package mensajes;

public enum MensType {
	MENSAJE_CONEXION, MENSAJE_LISTA_USARIOS, MENSAJE_CERRAR_CONEXION,
	MENSAJE_PEDIR_FICHERO, MENSAJE_PREPARADO_CLIENTESERVIDOR,
	MENSAJE_CONFIRMACION_CONEXION, MENSAJE_CONFIRMACION_LISTA_USUARIOS,
	MENSAJE_EMITIR_FICHERO, MENSAJE_PREPARADO_SERVIDORCLIENTE,
	MENSAJE_CONFIRMACION_CERRAR_CONEXION
}
