package mensajes;

public enum MensType {
	MENSAJE_CONEXION, MENSAJE_CONFIRMACION_CONEXION,
	MENSAJE_LISTA_USUARIOS, MENSAJE_CONFIRMACION_LISTA_USUARIOS, 
	MENSAJE_LISTA_ARCHIVOS, MENSAJE_CONFIRMACION_LISTA_ARCHIVOS, 
	MENSAJE_CERRAR_CONEXION,MENSAJE_CONFIRMACION_CERRAR_CONEXION, 
	MENSAJE_PEDIR_FICHERO, MENSAJE_EMITIR_FICHERO,
	MENSAJE_PREPARADO_EMISORCS, MENSAJE_PREPARADO_EMISORSC,
	
	
}
